version: 2
before:
  hooks:
    - go mod tidy
    - which nix-build
    - bash -c 'source /nix/var/nix/profiles/default/etc/profile.d/nix.sh && cat $(nix-build ./nix/manifests.nix --argstr imageName banhcanh/maxtac --argstr imageTag v{{ .Version }})/bundle.yaml > bundle.yaml'
builds:
  - binary: maxtac
    main: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
archives:
  - formats: ['tar.gz']
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_v{{- .Version }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - README.md
      - LICENSE
release:
  extra_files:
    - glob: ./bundle.yaml
