---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - maxtac.vtk.io
  resources:
  - accesses
  - clusteraccesses
  - clusterexternalaccesses
  - externalaccesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maxtac.vtk.io
  resources:
  - accesses/finalizers
  - clusteraccesses/finalizers
  - clusterexternalaccesses/finalizers
  - externalaccesses/finalizers
  verbs:
  - update
- apiGroups:
  - maxtac.vtk.io
  resources:
  - accesses/status
  - clusteraccesses/status
  - clusterexternalaccesses/status
  - externalaccesses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
